#a = 'Pedra'
#b = 'Papel'
#c = 'Tesoura'
#d = 1.1
#formato = 'a={nome1} b={nome2} c={nome3} d={nome4:.2f}'.format(nome1=a, nome2=b,nome3=c, nome4=d)
#print (formato)
   
#OU
#a = 'AAAAA'
#b = 'BBBBBB'
#c = 1.1
#string = 'b={nome2} a={nome1} a={nome1} c={nome3:.2f}'
#formato = string.format(
#    nome1=a, nome2=b, nome3=c
#)
#print(formato)
a="AAA"
b="BBB"
c= 1.10000
string = "a={nome1} b={nome2} c={nome3:.2f}".format(nome1=a, nome2=b, nome3=c,)
formato = string. format(
    nome1=a, nome2=b, nome=c
)
print(formato)