condicao1 = False
condicao2 = False
condicao3 = True
condicao4 = False
condicao5 = False

if condicao1:
    print ("Código para condição 1")
    print ("Código para condição 1")
elif condicao2:
    print("Código para condição 2")
elif condicao3:
    print("Código para condição 3")
elif condicao4:
    print("Código para condição 4")
elif condicao5:
    print("Código para condição 5")
else:
    print("Nenhuma condição foi feita")
if 10 == 10:
    print("Outro if")

print("fora do if")