# Operadores de atribuição
# = += -= /= //= **= %=

contador_1 = 5
contador_2 = 40
contador_3 = 10
contador_4 = 10
contador_5 = 10
contador_6 = 2
contador_7 = 10

contador_1 = 9
print (contador_1)

contador_2 += 9
print (contador_2)

contador_3 -= 5
print (contador_3)

contador_4 /= 9
print (contador_4)

contador_5 //= 5
print (contador_5)

contador_6 **= 10
print (contador_6)

contador_7 %= 2
print (contador_7)