adicao = 10 + 10
print ('adição', adicao)

subtraçao = 20 - 10
print ('subtração', subtraçao)

multiplicacao = 5 * 5
print ('multiplição', multiplicacao)

divisao = 10 / 2.2
print('divisão', divisao)

divisao_inteira = 10 // 2.2
print('Divisão inteira', divisao_inteira)

exponenciacao = 2 ** 10
print ('exponenciação', exponenciacao)

modulo = 55 % 2 #resto da divisão
print("Modulo", modulo)

#print(10 % 8 == 0)
#print(16 % 8 == 0)
#print(10 % 2 == 0)
#print(15 % 2 == 0)
#print(16 % 2 == 0)