#p_valor   = input("Digite um valor: ")
#s_valor   = input ("Digite outro valor: ")
 
#if p_valor > s_valor:
    #print("O primeiro valor é maior")
#elif p_valor < s_valor:
    #print("O segundo valor é menor")
#else:
    #print("Os valores são iguais")#



#primeiro_valor = input('Digite um valor: ')
#segundo_valor = input('Digite outro valor: ')

#if primeiro_valor >= segundo_valor:
    #print(
        #f'{primeiro_valor=} é maior ou igual '
        #f'ao que {segundo_valor=}'
    #)
#else:
    #print(
        #f'{segundo_valor=} é maior '
        #f'do que {primeiro_valor=}'
    #)

p_valor = input ("Digite um valor: ")
s_valor = input ("Digite outro valor: ")

if p_valor >= s_valor:
    print ( f'{p_valor=} é maior ou igual '
           f'ao que {s_valor=}')
else:
    print(
        f"{s_valor=} é maior "
        f'do que {p_valor=}'    
    )



